version: "3.8"

services:
  database:
    image: mongo:6
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://database:27017/mydb
      - PAYPAL_CLIENT_ID=<your_paypal_client_id>
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reload in container

volumes:
  mongo_data:
