apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: proshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: khalidali07/frontend-app:null-3
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service.proshop.svc.cluster.local"   # 👈 internal DNS
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: proshop
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
