apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: proshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}   # 🚨 temp storage only
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: proshop
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017