apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: proshop
type: Opaque
data:
  MONGO_URI: bW9uZ29kOi8vbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L3Byb3Nob3A=   # "mongodb://mongodb-service:27017/proshop"
  JWT_SECRET: MTIzNjc1YmM=   # "123675bc"
  PAYPAL_CLIENT_ID: PHlvdXJfcGF5cGFsX2NsaWVudF9pZD4=   # "<your_paypal_client_id>"
  PAYPAL_APP_SECRET: PHlvdXJfcGF5cGFsX3NlY3JldD4=     # "<your_paypal_secret>"
